// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB66HBZOMq_llxIsAMwCgkZQIAOMeu-Wk',
    appId: '1:477894858659:web:a98d250f564eff22b96c16',
    messagingSenderId: '477894858659',
    projectId: 'gestaoprojecto-b41ff',
    authDomain: 'gestaoprojecto-b41ff.firebaseapp.com',
    storageBucket: 'gestaoprojecto-b41ff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzFNYa50H99VMPR7nx4nw7XRxy7YHX7Ss',
    appId: '1:477894858659:android:fd5ba89124117359b96c16',
    messagingSenderId: '477894858659',
    projectId: 'gestaoprojecto-b41ff',
    storageBucket: 'gestaoprojecto-b41ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGsolneFu8cgm1DwqupbXQHCvg2ia15OY',
    appId: '1:477894858659:ios:18060317dc867debb96c16',
    messagingSenderId: '477894858659',
    projectId: 'gestaoprojecto-b41ff',
    storageBucket: 'gestaoprojecto-b41ff.appspot.com',
    iosBundleId: 'com.example.helloFlutterMacApp',
  );
}
